name: Test build

on:
    push:
        branches:
            - master
            - develop
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04]
        steps:
        - uses: actions/checkout@master
        # - name: Install Prereqs
        #   run: |
        #     pip install --no-cache-dir docker-py
        #     echo "Python3 vvvv"
        #     pip list
        - name: Install Hass.io
          run: |
            pip3 install --no-cache-dir docker-py
            ansible-playbook  --connection=local -i .github/hosts.ini -e 'ansible_python_interpreter=/usr/bin/python3' .github/playbook.yml
        - name: Simple check
          run: |
            docker-compose --version
            docker ps
            RESULT=`docker ps |grep hassio`
            echo "$RESULT"
            if [ -z "$RESULT" ]; then echo "Hassio is not running."; exit 1 ;fi
